### ISSUE TITLE
Template Page have wrong links

### ISSUE THREAD

**Issue by HansUXdev** [foundation/foundation-sites#12099]
## Description

The images for each template have inaccurate links and return a 404.

Main pages: https://get.foundation/templates.html

It currently goes too to: 
- https://get.foundation/templates-previews-sites-f6/news-magazine.html

It should have the same url as the button and direct to:
- https://get.foundation/templates-previews-sites-f6-xy-grid/news-magazine.html

...

## Possible Solution

Not sure how this is built but changing how the final HTML is output is generated could help.

Front-Matter:
```yml
-  name: News
    img: "assets/img/sites-templates/f6-template-news-mag.svg"
    url: "news-magazine.html"
-  name: Real Estate
    img: "https://get.foundation/assets/img/sites-templates/f6-template-realestate.svg"
    url: "https://get.foundation/templates-previews-sites-f6-xy-grid/real-estate.html"
```

```html
<div class="column text-center">
    <a class="img-link" href={{url}}><img class="thumbnail" src={{img}}></a>
     <h5>{{name}}</h5>
     <p>{{description}}</p>
     <a href="downloads/templates-sites/{{url}}" download="" class="button all-sites-download">Download</a>
      <a href="templates-previews-sites-f6-xy-grid/{{url}}" class="button secondary-demo-button">See Demo</a>      
</div>
```

As an unrelated sidenote, foundation 6 doesn't have any [resources for prototyping](https://get.foundation/sites/resources.html) 

So I was wondering if anyone else be interested in:
1. using the template svgs and or images of the building blocks as either printable paper prototypes 
2. added to [draw.io vscode extension](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio)?

I'm already doing the first part but I probably wont do the second part if there isn't any need.
...

## Checklist

- [x ] I have read and follow the CONTRIBUTING.md document.
searched is:issue is:open template 
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.
