### ISSUE TITLE
Possibility to setup the callout lightness as optional parameter of the mixin

### ISSUE THREAD

**Issue by zeleznypa** [foundation/foundation-sites#12114]
Since the callouts are also used as "sections" (_like footer in [ecommerce](https://get.foundation/downloads/templates-sites/ecommerce.html) template_), it will be useful to have a possibility to have "lighter" version for alerts and "darker" version for the sections. Because of that, it will be useful to change the [`callout-style`](https://github.com/foundation/foundation-sites/blob/b8917a6b29c465ee79cfafad705aa78bf7f8545a/scss/components/_callout.scss#L70) by adding second optional parameter with the `$lightness` value:

```scss
/// Generate quick styles for a callout using a single color as a baseline.
/// @param {Color} $color [$callout-background] - Color to use.
/// @param {Number} $lightness [$callout-background-fade] - Lightnes level percent.
@mixin callout-style($color: $callout-background, $lightness: $callout-background-fade) {
  $background: scale-color($color, $lightness);

  background-color: $background;
  color: color-pick-contrast($background, ($callout-font-color, $callout-font-color-alt));
}
```
