### ISSUE TITLE
middle positioned labels do not correctly work

### ISSUE THREAD

**Issue by pine3ree** [foundation/foundation-sites#12142]
## What should happen?

The `<label>` should be centered vertically against the input element

## What happens instead?

The `<label>` element is vertically centered in its own box which is higher (42px in the example https://get.foundation/sites/docs/forms.html#label-positioning) than the input (39px). The label height changes (along with its line-height and font-size changes) make it impossible to stay centered.

## Possible Solution
```scss
.label.middle {
    padding: get-side($input-padding, 'top') 0 get-side($input-padding, 'bottom');
    line-height: ($input-font-size * unitless-calc($input-line-height))  - rem-calc(1);
}
```

## Test Case and/or Steps to Reproduce (for bugs)
https://get.foundation/sites/docs/forms.html#label-positioning
examine the label/inout heights with web-dev-tools and try changing the label font size

PS
Why is `- rem-calc(1)` used in input height calculation?
I usually add twice the border size to set the height of inputs to match button's height with same line-height, font-size, v-padding and v-border.

kind regards
